@startuml

!include https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml/themes/themes/catppuccin/latte-white.puml
' !include https://raw.githubusercontent.com/MikhailKravets/mkdocs_puml/themes/themes/catppuccin/mocha.puml

skinparam componentStyle rectangle

artifact "acme.ini.default" as inidefault
artifact "acme.ini" as ini
[ACME CSE] as cse
cse --> inidefault : 1. reads\ndefault\nconfiguration
cse --> ini : 2. reads\nconfig file

@enduml