@startuml
skinparam componentStyle rectangle

artifact "acme.ini.default" as inidefault
artifact "configuration\nvalues" as ini
[ACME CSE] as cse
[Zookeeper] as zk

cse .right.> zk : 2. reads remote \nconfiguration
cse ..> inidefault : 1. reads default\nconfiguration
zk ..> ini

@enduml